apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-config
  namespace: library
data:
  GRPC_PORT: "50052"
  KAFKA_BROKERS: "kafka-0.kafka.messaging.svc.cluster.local:9092"
  OTEL_COLLECTOR_ENDPOINT: ""
