apiVersion: v1
kind: ConfigMap
metadata:
  name: reservation-config
  namespace: library
data:
  GRPC_PORT: "50053"
  KAFKA_BROKERS: "kafka-0.kafka.messaging.svc.cluster.local:9092"
  CATALOG_GRPC_ADDR: "catalog.library.svc.cluster.local:50052"
  MAX_ACTIVE_RESERVATIONS: "5"
  OTEL_COLLECTOR_ENDPOINT: ""
