apiVersion: v1
kind: ConfigMap
metadata:
  name: search-config
  namespace: library
data:
  GRPC_PORT: "50054"
  KAFKA_BROKERS: "kafka-0.kafka.messaging.svc.cluster.local:9092"
  MEILI_URL: "http://meilisearch.data.svc.cluster.local:7700"
  CATALOG_GRPC_ADDR: "catalog.library.svc.cluster.local:50052"
