apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: library
data: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-catalog-secret
  namespace: library
data: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth-secret
  namespace: library
data: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-reservation-secret
  namespace: library
data: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: meilisearch-secret
  namespace: library
data: {}
