root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/"
  bin = "./tmp/main"
  delay = 1000
  exclude_dir = ["tmp", "vendor"]
  include_ext = ["go", "html", "css"]
  kill_delay = "0s"

[log]
  time = false

[misc]
  clean_on_exit = true
