services:
  catalog:
    build:
      context: ..
      dockerfile: services/catalog/Dockerfile.dev
    volumes:
      - ../services/catalog:/app/services/catalog
      - ../gen:/app/gen

  gateway:
    build:
      context: ..
      dockerfile: services/gateway/Dockerfile.dev
    volumes:
      - ../services/gateway:/app/services/gateway
