FROM golang:1.26-alpine

RUN go install github.com/air-verse/air@latest

WORKDIR /app

ENV GOWORK=off

COPY gen/ ./gen/
COPY pkg/auth/ ./pkg/auth/
COPY services/search/ ./services/search/

WORKDIR /app/services/search
RUN go mod download

CMD ["air", "-c", ".air.toml"]
