VERSION 0.8

FROM golang:1.26-alpine

WORKDIR /app

deps:
    COPY go.mod go.sum* ./
    COPY ../../+gen-mod/gen ../gen
    COPY ../../+pkg-auth-mod/pkg-auth ../pkg/auth
    ENV GOWORK=off
    RUN go mod download && (cd ../gen && go mod download) && (cd ../pkg/auth && go mod download)
    SAVE ARTIFACT go.mod AS LOCAL go.mod
    SAVE ARTIFACT go.sum AS LOCAL go.sum

src:
    FROM +deps
    COPY --dir cmd internal ./
    COPY ../../+gen-src/gen ../gen
    COPY ../../+pkg-auth-src/pkg-auth ../pkg/auth

lint:
    FROM +src
    COPY ../../+golangci-config/.golangci.yml ./
    RUN go build ./...
    RUN go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.8
    RUN golangci-lint run ./...

test:
    FROM +src
    RUN go test ./internal/service/... ./internal/handler/... ./internal/consumer/... ./internal/bootstrap/... -v -count=1

build:
    FROM +src
    RUN CGO_ENABLED=0 go build -o /bin/search ./cmd/
    SAVE ARTIFACT /bin/search

docker:
    FROM alpine:3.19
    COPY +build/search /usr/local/bin/search
    EXPOSE 50054
    ENTRYPOINT ["/usr/local/bin/search"]
    SAVE IMAGE search:latest
