FROM golang:1.26-alpine

RUN go install github.com/air-verse/air@latest

WORKDIR /app

ENV GOWORK=off

COPY gen/ ./gen/
COPY pkg/auth/ ./pkg/auth/
COPY services/reservation/ ./services/reservation/

WORKDIR /app/services/reservation
RUN go mod download

CMD ["air", "-c", ".air.toml"]
